import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import matter from 'gray-matter';
import { marked } from 'marked';
import type { DiaryArticle, DiaryHeading } from '../src/features/diary/diary-types';

export interface GenerateDiaryContentOptions {
  sourceDirectory: string;
  outputFile: string;
}

export function isMainModule(moduleUrl: string, commandPath: string | undefined): boolean {
  return commandPath !== undefined && moduleUrl === pathToFileURL(path.resolve(commandPath)).href;
}

function getRequiredString(value: unknown, field: string, filename: string): string {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`${filename}: frontmatter field \"${field}\" must be a non-empty string.`);
  }
  return value;
}

function getDate(value: unknown, field: string, filename: string): string {
  const date = value instanceof Date ? value : new Date(String(value));
  if (Number.isNaN(date.getTime())) {
    throw new Error(`${filename}: frontmatter field \"${field}\" must be a valid date.`);
  }
  return date.toISOString().slice(0, 10);
}

function slugify(value: string, usedSlugs: Map<string, number>): string {
  const base = value
    .replace(/<[^>]+>/g, '')
    .trim()
    .toLocaleLowerCase()
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .replace(/[\s-]+/g, '-') || 'section';
  const occurrence = usedSlugs.get(base) ?? 0;
  usedSlugs.set(base, occurrence + 1);
  return occurrence === 0 ? base : `${base}-${occurrence + 1}`;
}

function extractHeadings(markdown: string): DiaryHeading[] {
  const usedSlugs = new Map<string, number>();
  const headings: DiaryHeading[] = [];

  for (const line of markdown.split(/\r?\n/)) {
    const match = /^(#{2,5})\s+(.+?)\s*#*\s*$/.exec(line);
    if (!match) continue;
    const depth = match[1].length as 2 | 3 | 4 | 5;
    const text = match[2].replace(/[`*_]/g, '').trim();
    headings.push({ depth, slug: slugify(text, usedSlugs), text });
  }

  return headings;
}

function addHeadingIds(html: string, headings: DiaryHeading[]): string {
  let headingIndex = 0;
  return html.replace(/<h([2-5])>([\s\S]*?)<\/h\1>/g, (match, depth: string) => {
    const heading = headings[headingIndex++];
    if (!heading || heading.depth !== Number(depth)) return match;
    return `<h${depth} id="${heading.slug}">${match.slice(4, -5)}</h${depth}>`;
  });
}

function toArticle(filename: string, markdown: string): Promise<DiaryArticle | undefined> {
  const parsed = matter(markdown);
  const title = getRequiredString(parsed.data.title, 'title', filename);
  const description = getRequiredString(parsed.data.description, 'description', filename);
  const publishedAt = getDate(parsed.data.publishedAt, 'publishedAt', filename);
  const draft = parsed.data.draft === true;
  if (parsed.data.draft !== undefined && typeof parsed.data.draft !== 'boolean') {
    throw new Error(`${filename}: frontmatter field \"draft\" must be a boolean.`);
  }
  if (draft) return Promise.resolve(undefined);

  const headings = extractHeadings(parsed.content);
  const id = path.basename(filename, path.extname(filename));
  return Promise.resolve(marked.parse(parsed.content)).then((html) => ({
    id,
    title,
    description,
    publishedAt,
    ...(parsed.data.updatedAt ? { updatedAt: getDate(parsed.data.updatedAt, 'updatedAt', filename) } : {}),
    ...(typeof parsed.data.cover === 'string' ? { cover: parsed.data.cover } : {}),
    draft,
    html: addHeadingIds(html, headings),
    headings,
  }));
}

function generatedModule(articles: DiaryArticle[]): string {
  return `// This file is generated by scripts/generate-diary-content.ts. Do not edit.\nimport type { DiaryArticle } from '../features/diary/diary-types';\n\nexport const diaryArticles: DiaryArticle[] = ${JSON.stringify(articles, null, 2)};\n`;
}

export async function generateDiaryContent({ sourceDirectory, outputFile }: GenerateDiaryContentOptions): Promise<DiaryArticle[]> {
  const filenames = (await fs.readdir(sourceDirectory))
    .filter((filename) => /\.mdx?$/i.test(filename) && filename !== '_template.md')
    .sort();
  const candidates = await Promise.all(filenames.map(async (filename) => toArticle(
    filename,
    await fs.readFile(path.join(sourceDirectory, filename), 'utf8'),
  )));
  const articles = candidates
    .filter((article): article is DiaryArticle => article !== undefined)
    .sort((left, right) => right.publishedAt.localeCompare(left.publishedAt));

  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.writeFile(outputFile, generatedModule(articles), 'utf8');
  return articles;
}

if (isMainModule(import.meta.url, process.argv[1])) {
  const rootDirectory = path.resolve(import.meta.dirname, '..');
  await generateDiaryContent({
    sourceDirectory: path.join(rootDirectory, 'src/content/diary'),
    outputFile: path.join(rootDirectory, 'src/generated/diary.ts'),
  });
}
